export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const FETCH_POPULAR_MOVIES_SUCCESS = "FETCH_POPULAR_MOVIES_SUCCESS";
export const FETCH_POPULAR_MOVIES_FAILURE = "FETCH_POPULAR_MOVIES_FAILURE";
export const FETCH_REVENUE_MOVIE = "FETCH_REVENUE_MOVIE";
export const FETCH_REVENUE_MOVIE_SUCCESS = "FETCH_REVENUE_MOVIE_SUCCESS";
export const FETCH_REVENUE_MOVIE_FAILURE = "FETCH_REVENUE_MOVIE_FAILURE";
