export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES_SWAPII";
export const FETCH_POPULAR_MOVIES_SUCCESS =
  "FETCH_POPULAR_MOVIES_SUCCESS_SWAPII";
export const FETCH_POPULAR_MOVIES_FAILURE =
  "FETCH_POPULAR_MOVIES_FAILURE_SWAPII";
export const FETCH_REVENUE_MOVIE = "FETCH_REVENUE_MOVIE_SWAPII";
export const FETCH_REVENUE_MOVIE_SUCCESS = "FETCH_REVENUE_MOVIE_SUCCESS_SWAPII";
export const FETCH_REVENUE_MOVIE_FAILURE = "FETCH_REVENUE_MOVIE_FAILURE_SWAPII";
export const SWITCH_VIEW_POP = "SWITCH_VIEW_LIST_SWAPII";
export const SWITCH_VIEW_REV = "SWITCH_VIEW_REV_SWAPII";
